
import { Aircraft, AircraftSize, PortfolioItem } from './types';

export const AIRCRAFT_DATA: Aircraft[] = [
  {
    id: '1',
    model: 'Citation Longitude',
    manufacturer: 'Cessna',
    price: 26000000,
    range: 3500,
    speed: 483,
    capacity: 12,
    size: AircraftSize.SUPER_MIDSIZE,
    description: 'The super-midsize Citation Longitude is designed with your business and return on investment in mind.',
    imageUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 3400,
    cabinZones: 2,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: false
  },
  {
    id: '2',
    model: 'G700',
    manufacturer: 'Gulfstream',
    price: 75000000,
    range: 7500,
    speed: 516,
    capacity: 19,
    size: AircraftSize.ULTRA_LONG,
    description: 'The flagship of the Gulfstream fleet, offering unparalleled range, speed, and luxury with up to five living areas.',
    imageUrl: 'https://images.unsplash.com/photo-1583662630922-83020697924c?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 6800,
    cabinZones: 5,
    hasBedroom: true,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  },
  {
    id: '3',
    model: 'Phenom 300E',
    manufacturer: 'Embraer',
    price: 9500000,
    range: 2010,
    speed: 464,
    capacity: 6,
    size: AircraftSize.LIGHT,
    description: 'The world\'s best-selling light jet for 11 consecutive years, featuring the largest windows in its class.',
    imageUrl: 'https://images.unsplash.com/photo-1620067925093-801122da1688?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 1900,
    cabinZones: 1,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: false,
    hasOven: false,
    hasMicrowave: false,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: false
  },
  {
    id: '4',
    model: 'Global 7500',
    manufacturer: 'Bombardier',
    price: 73000000,
    range: 7700,
    speed: 516,
    capacity: 19,
    size: AircraftSize.ULTRA_LONG,
    description: 'The largest and longest-range business jet in the world, featuring a full-size kitchen and a master suite.',
    imageUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 7100,
    cabinZones: 4,
    hasBedroom: true,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  },
  {
    id: '5',
    model: 'PC-12 NGX',
    manufacturer: 'Pilatus',
    price: 5400000,
    range: 1803,
    speed: 290,
    capacity: 9,
    size: AircraftSize.TURBOPROP,
    description: 'The world\'s most versatile and popular single-engine turboprop, now with a completely redesigned cabin.',
    imageUrl: 'https://images.unsplash.com/photo-1521464302485-72fc85b09000?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 950,
    cabinZones: 1,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: false,
    hasOven: false,
    hasMicrowave: false,
    hasColdStorage: false,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  },
  {
    id: '6',
    model: 'Falcon 8X',
    manufacturer: 'Dassault',
    price: 58000000,
    range: 6450,
    speed: 475,
    capacity: 14,
    size: AircraftSize.LARGE_CABIN,
    description: 'The ultimate combination of efficiency, versatility, and tri-jet safety for non-stop global travel.',
    imageUrl: 'https://images.unsplash.com/photo-1464039397811-476f652a343b?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 4200,
    cabinZones: 3,
    hasBedroom: true,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: false
  },
  {
    id: '7',
    model: 'Citation CJ3',
    manufacturer: 'Cessna',
    price: 8000000,
    range: 1875,
    speed: 416,
    capacity: 7,
    size: AircraftSize.LIGHT,
    description: 'The Citation CJ3 delivers exceptional performance and reliability for regional short-to-mid range missions.',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 1500,
    cabinZones: 1,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: false,
    hasOven: false,
    hasMicrowave: false,
    hasColdStorage: true,
    hasCoffeeMachine: false,
    hasLargeStorage: false
  },
  {
    id: '8',
    model: 'Phenom 300',
    manufacturer: 'Embraer',
    price: 9500000,
    range: 1971,
    speed: 453,
    capacity: 8,
    size: AircraftSize.LIGHT,
    description: 'High performance meets premium comfort in this industry-leading light jet with two cabin compartments.',
    imageUrl: 'https://images.unsplash.com/photo-1620986506308-412754d92410?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 1800,
    cabinZones: 2,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: false,
    hasOven: false,
    hasMicrowave: false,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: false
  },
  {
    id: '9',
    model: 'Hawker 800XP',
    manufacturer: 'Hawker',
    price: 13000000,
    range: 2642,
    speed: 447,
    capacity: 8,
    size: AircraftSize.MIDSIZE,
    description: 'A rugged and reliable midsize jet known for its spacious cabin and three distinct compartments.',
    imageUrl: 'https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 2200,
    cabinZones: 3,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: false,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  },
  {
    id: '10',
    model: 'Citation XLS+',
    manufacturer: 'Cessna',
    price: 12500000,
    range: 2100,
    speed: 441,
    capacity: 9,
    size: AircraftSize.MIDSIZE,
    description: 'The world’s best-selling business jet, combining transcontinental range with first-class cabin comfort.',
    imageUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 2100,
    cabinZones: 2,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: false,
    hasOven: true,
    hasMicrowave: false,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: false
  },
  {
    id: '11',
    model: 'G280',
    manufacturer: 'Gulfstream',
    price: 25000000,
    range: 3600,
    speed: 482,
    capacity: 10,
    size: AircraftSize.SUPER_MIDSIZE,
    description: 'Unmatched in its class, the G280 offers transcontinental speed and agility with four cabin zones.',
    imageUrl: 'https://images.unsplash.com/photo-1620067925093-801122da1688?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 3000,
    cabinZones: 4,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  },
  {
    id: '12',
    model: 'Challenger 350',
    manufacturer: 'Bombardier',
    price: 27000000,
    range: 3200,
    speed: 470,
    capacity: 10,
    size: AircraftSize.SUPER_MIDSIZE,
    description: 'Designed for the optimal passenger experience with a flat floor and the widest cabin in its class.',
    imageUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 3200,
    cabinZones: 3,
    hasBedroom: false,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: false
  },
  {
    id: '13',
    model: 'Gulfstream G650',
    manufacturer: 'Gulfstream',
    price: 65000000,
    range: 7000,
    speed: 516,
    capacity: 18,
    size: AircraftSize.LARGE_CABIN,
    description: 'A masterpiece of aviation engineering, offering extreme range and high speed with five luxurious zones.',
    imageUrl: 'https://images.unsplash.com/photo-1583662630922-83020697924c?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 5000,
    cabinZones: 5,
    hasBedroom: true,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  },
  {
    id: '14',
    model: 'Global 7500 (Legacy)',
    manufacturer: 'Bombardier',
    price: 75000000,
    range: 7700,
    speed: 516,
    capacity: 19,
    size: AircraftSize.LARGE_CABIN,
    description: 'The ultimate flagship for global travelers, providing six cabin compartments for work, dining, and sleep.',
    imageUrl: 'https://images.unsplash.com/photo-1464039397811-476f652a343b?auto=format&fit=crop&q=80&w=800',
    operatingCostPerHour: 5500,
    cabinZones: 6,
    hasBedroom: true,
    hasEnclosedLavatory: true,
    hasSlidingDividers: true,
    hasOven: true,
    hasMicrowave: true,
    hasColdStorage: true,
    hasCoffeeMachine: true,
    hasLargeStorage: true
  }
];

export const PORTFOLIO_DATA: PortfolioItem[] = [
  {
    id: 'p1',
    model: 'Gulfstream G650ER',
    location: 'Zurich, CH',
    year: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&q=80&w=800',
    clientStory: 'An impeccable long-range heavy jet. Professionally managed with low airframe hours.',
    specs: '7,500 nm | 16 PAX'
  },
  {
    id: 'p2',
    model: 'Challenger 350',
    location: 'Miami, US',
    year: 'Listed',
    imageUrl: 'https://images.unsplash.com/photo-1620067925093-801122da1688?auto=format&fit=crop&q=80&w=800',
    clientStory: 'High-spec cabin configuration with Ka-band internet and full galley upgrades.',
    specs: '3,200 nm | 9 PAX'
  },
  {
    id: 'p3',
    model: 'Pilatus PC-24',
    location: 'Aspen, US',
    year: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1521464302485-72fc85b09000?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Rugged versatility meets jet performance. Ideal for owners requiring high-altitude field access.',
    specs: '2,000 nm | 8 PAX'
  },
  {
    id: 'p4',
    model: 'Global 7500',
    location: 'London, UK',
    year: 'Exclusive',
    imageUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Flagship capability with a master suite and full crew rest area for global missions.',
    specs: '7,700 nm | 19 PAX'
  },
  {
    id: 'p5',
    model: 'Phenom 100EV',
    location: 'São Paulo, BR',
    year: 'New List',
    imageUrl: 'https://images.unsplash.com/photo-1583662630922-83020697924c?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Perfect entry-level jet with Garmin G3000 avionics and stunning OvalLite interior.',
    specs: '1,178 nm | 4 PAX'
  },
  {
    id: 'p6',
    model: 'Falcon 2000LXS',
    location: 'Dubai, UAE',
    year: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1464039397811-476f652a343b?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Widebody comfort with high efficiency. Steep approach certified for London City operations.',
    specs: '4,000 nm | 10 PAX'
  },
  {
    id: 'p7',
    model: 'Citation Latitude',
    location: 'Chicago, US',
    year: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Midsize performance with a flat floor and the most spacious cabin in its class.',
    specs: '2,700 nm | 9 PAX'
  },
  {
    id: 'p8',
    model: 'Learjet 75 Liberty',
    location: 'Dallas, US',
    year: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Legendary speed and style. A pristine example of light jet performance with modern avionics.',
    specs: '2,040 nm | 8 PAX'
  },
  {
    id: 'p9',
    model: 'Hawker 900XP',
    location: 'Berlin, DE',
    year: 'Reduced',
    imageUrl: 'https://images.unsplash.com/photo-1620986506308-412754d92410?auto=format&fit=crop&q=80&w=800',
    clientStory: 'Excellent maintenance history. A rugged, reliable midsize jet with a highly sought-after cabin.',
    specs: '2,900 nm | 8 PAX'
  }
];
